services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    command: bash -c "./db-setup.sh db bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - es
    environment:
      DATABASE_HOST: db
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      RAILS_ENV: development
      ELASTICSEARCH_URL: http://es:9200
    networks:
      - app_network

  redis:
    image: redis:6.2.6
    command: redis-server
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
      - es
    volumes:
      - ".:/app"
    environment:
      REDIS_URL: ${REDIS_URL}
      RAILS_ENV: development

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - node.name=es
      - cluster.name=cluster
      - discovery.seed_hosts=es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
    networks:
    - app_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    ports:
      - 5601:5601
    networks:
    - app_network

volumes:
  mysql_data:
  redis:
  es:

networks:
  app_network:
    driver: bridge
